choco install 7zip -y
choco install 7zip.install -y
choco install chocolatey -y
choco install chocolatey-core.extension -y
choco install chocolatey-windowsupdate.extension -y
choco install docker-desktop -y
choco install dropbox -y
choco install erlang -y
choco install Firefox -y
choco install freemind -y
choco install git -y
choco install git.install -y
choco install groovy -y
choco install intellijidea-ultimate -y
choco install jdk8 -y
choco install KB2919355 -y
choco install KB2919442 -y
choco install KB2999226 -y
choco install keepass-classic -y
choco install kubernetes-cli -y
choco install kubernetes-helm -y
choco install maven -y
choco install miniconda -y
choco install Minikube -y
choco install nodejs -y
choco install nodejs.install -y
choco install p4v -y
choco install postman -y
choco install rabbitmq -y
choco install soapui -y
choco install sublimetext3 -y
choco install textpad -y
choco install thunderbird -y
choco install vagrant -y
choco install vlc -y
choco install winmerge -y
